name: Сервис БРС ЮФУ
description: Приложение для доступа к сервису Балльно-рейтинговой системы ЮФУ
full_description: 'Удобное приложение для доступа к сервису Балльно-рейтинговой системы Южного федерального 
университета, которое позволяет студентам просматривать свои баллы и посещаемость по дисциплинам, а преподавателям 
выставлять баллы и вести учёт посещаемости, создавая занятия и проставляя присутствие студентов на них.'
android: https://play.google.com/store/apps/details?id=ru.mihaxxx.grade
iOS: https://apps.apple.com/app/%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81-%D0%B1%D1%80%D1%81-%D1%8E%D1%84%D1%83/id6449784369
web: false
screenshots:
  - 1.jpeg
  - 2.jpeg
  - 3.jpeg
  - 4.jpeg
  - 5.jpeg
  - 6.jpeg
  - 7.jpeg
#producthunt: https://telegra.ph/Replace-this-link-07-23
#companies:
#  - url: https://telegra.ph/Replace-this-link-07-23
#    image: androidpolice.png
#  - url: https://telegra.ph/Replace-this-link-07-23
#    image: producthunt.png
